# Generated by Django 5.2.12 on 2026-03-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('analytic_score', models.FloatField()),
                ('immersion_score', models.FloatField()),
                ('critical_score', models.FloatField()),
                ('empathy_score', models.FloatField()),
                ('practical_score', models.FloatField()),
                ('expansion_score', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('model_version', models.CharField(max_length=50)),
                ('analyzed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookRbtiStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('avg_review_score', models.FloatField(default=0.0)),
                ('positive_ratio', models.FloatField(default=0.0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbti_stats', to='books.book')),
            ],
        ),
    ]
