# Generated by Django 5.2.12 on 2026-03-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('rbti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrbtistat',
            name='rbti_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_stats', to='rbti.rbtitype'),
        ),
    ]
