# Generated by Django 5.2.12 on 2026-03-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('rbti', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrbtistat',
            name='representative_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_in_stats', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewanalysisresult',
            name='inferred_rbti_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_analysis_results', to='rbti.rbtitype'),
        ),
        migrations.AddField(
            model_name='reviewanalysisresult',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='reviews.review'),
        ),
        migrations.AddConstraint(
            model_name='bookrbtistat',
            constraint=models.UniqueConstraint(fields=('book', 'rbti_type'), name='unique_book_rbti_stat'),
        ),
    ]
