# Generated by Django 5.2.12 on 2026-05-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_initial'),
        ('reading', '0002_remove_userbook_page_count'),
    ]

    operations = [
    ]
