# Generated by Django 5.2.12 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbook",
            name="book_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userbook",
            name="page_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
