import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FE',
  },
  headerScrollSection: {
    flex: 1,
    backgroundColor: '#F8F9FE',
  },
  buttonSection: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    zIndex: 10,
  },
  header: {
    height: 56,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 28,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
    color: '#24262B',
  },
  headerRight: {
    width: 28,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 120,
  },
  coverCard: {
    backgroundColor: '#FFF6EA',
    borderRadius: 22,
    alignItems: 'center',
    paddingTop: 22,
    paddingBottom: 18,
    marginBottom: 20,
  },
  coverImageWrap: {
    marginBottom: 12,
  },
  coverImage: {
    borderRadius: 0,
    backgroundColor: '#FFD7A2',
  },
  coverPlaceholder: {
    backgroundColor: '#FFECD2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coverTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#22242A',
    marginBottom: 4,
  },
  coverAuthor: {
    fontSize: 13,
    color: '#666A73',
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#24262B',
    marginBottom: 14,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitleCompact: {
    fontSize: 15,
    fontWeight: '700',
    color: '#24262B',
  },
  recordEmptyBox: {
    minHeight: 56,
    justifyContent: 'center',
  },
  recordEmptyText: {
    fontSize: 13,
    color: '#8A8E98',
    lineHeight: 20,
    textAlign: 'center',
  },
  recordDetailWrap: {
    gap: 12,
  },
  recordStatusActionInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  recordFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  recordFieldLabel: {
    fontSize: 16,
    color: '#555A63',
  },
  recordFieldValueBox: {
    minWidth: 86,
    minHeight: 30,
    borderRadius: 8,
    backgroundColor: '#FFF6EA',
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordTypeValueWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  recordFieldValueText: {
    fontSize: 14,
    color: '#2D2F36',
  },
  recordDatePickerWrap: {
    minWidth: 86,
    minHeight: 30,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordDatePickerTouchLayer: {
    ...StyleSheet.absoluteFillObject,
    width: 86,
    height: 30,
    opacity: 0.02,
  },
  recordLengthInputWrap: {
    width: 70,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 18,
  },
  recordLengthInput: {
    width: 44,
    height: 18,
    fontSize: 14,
    lineHeight: 18,
    color: '#2D2F36',
    textAlign: 'right',
    textAlignVertical: 'center',
    paddingVertical: 0,
    paddingHorizontal: 0,
    margin: 0,
    transform: [{ translateY: -1 }],
  },
  recordLengthSuffix: {
    width: 18,
    marginLeft: 4,
    fontSize: 14,
    lineHeight: 18,
    color: '#2D2F36',
    includeFontPadding: false,
    textAlign: 'left',
  },
  infoBox: {
    borderWidth: 1,
    borderColor: '#B8B8BE',
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
    minHeight: 100,
    justifyContent: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  infoLabel: {
    fontSize: 13,
    color: '#666A73',
  },
  infoValue: {
    fontSize: 13,
    color: '#2A2C31',
  },
  descriptionText: {
    fontSize: 13,
    color: '#3A3D43',
    lineHeight: 20,
  },
  moreButton: {
    marginTop: 10,
    alignSelf: 'center',
    paddingVertical: 4,
  },
  moreButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#F2A637',
  },
  quoteNotePreviewBox: {
    borderRadius: 12,
    backgroundColor: '#F8F9FE',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  quoteNotePreviewBoxGap: {
    marginBottom: 8,
  },
  quoteNotePreviewRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  quoteNotePreviewText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 20,
    color: '#3A3D43',
    marginBottom: 0,
  },
  quoteNotePageInlineText: {
    fontSize: 12,
    lineHeight: 20,
    color: '#8B909B',
    marginLeft: 8,
    includeFontPadding: false,
  },
  myReviewStarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  myReviewStarIcon: {
    marginRight: 6,
  },
  myReviewContentText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#3A3D43',
  },
  chipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  positiveRbtiBox: {
    minHeight: 78,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFE4A8',
    borderRadius: 8,
    backgroundColor: '#FFFCF5',
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 14,
  },
  positiveRbtiIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFF4DA',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  positiveRbtiTextWrap: {
    flex: 1,
  },
  positiveRbtiLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9A7430',
    marginBottom: 3,
  },
  positiveRbtiTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#292C31',
    marginBottom: 2,
  },
  positiveRbtiMeta: {
    fontSize: 12,
    color: '#858B96',
  },
  chip: {
    backgroundColor: '#FFF6EA',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chipActive: {
    backgroundColor: '#FEC54B',
  },
  chipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#E67F1E',
  },
  chipTextActive: {
    color: '#FFFFFF',
  },
  reviewBox: {
    backgroundColor: '#F1F3FA',
    borderRadius: 16,
    padding: 12,
  },
  reviewBoxGap: {
    marginBottom: 10,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#F9DFC0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  reviewHeaderText: {
    flex: 1,
  },
  reviewNickname: {
    fontSize: 12,
    fontWeight: '700',
    color: '#31343A',
    marginBottom: 4,
  },
  reviewBody: {
    fontSize: 12,
    lineHeight: 18,
    color: '#666A73',
  },
  bottomButtonWrap: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 40,
    zIndex: 3,
  },
  bottomSolidOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    zIndex: 1,
  },
  bottomFadeOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 2,
  },
  addButton: {
    height: 54,
    borderRadius: 27,
    backgroundColor: '#F5C24B',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#E7BE63',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  addButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'transparent',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(20, 24, 32, 0.42)',
  },
  infoSheet: {
    height: '82%',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 28,
  },
  infoSheetTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#24262B',
    textAlign: 'center',
    marginBottom: 20,
  },
  infoSheetBox: {
    borderWidth: 1,
    borderColor: '#B8B8BE',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
  },
  infoSheetDescriptionScroll: {
    flex: 1,
  },
  infoSheetDescriptionContent: {
    paddingBottom: 20,
  },
  infoSheetDescriptionText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#3A3D43',
  },
  sheetConfirmButton: {
    height: 54,
    borderRadius: 27,
    backgroundColor: '#F5C24B',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  sheetConfirmButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  recordSheetOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'flex-end',
  },
  recordSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(20, 24, 32, 0.42)',
  },
  recordSheetContainer: {
    paddingTop: 8,
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  recordSheetPrimaryButton: {
    height: 54,
    borderRadius: 27,
    backgroundColor: '#FFF6EA',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 0,
    marginBottom: 10,
  },
  recordSheetPrimaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#F29A2E',
  },
  recordSheetDangerSoftButton: {
    height: 54,
    borderRadius: 27,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  recordSheetDangerSoftButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#F04A3A',
  },
  recordSheetCancelButton: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 30,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#FFF6EA',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  recordSheetCancelButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#F29A2E',
  },
});
