# Generated by Django 5.2.12 on 2026-03-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('external_api_source', models.CharField(blank=True, max_length=30)),
                ('external_api_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('translator', 'Translator'), ('editor', 'Editor')], default='author', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='books.BookAuthor', to='books.author'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author', 'role'), name='unique_book_author_role'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_api_source', ''), _negated=True), models.Q(('external_api_id', ''), _negated=True)), fields=('external_api_source', 'external_api_id'), name='unique_book_external_source_id'),
        ),
    ]
