# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="kdc",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="book",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
