# Generated by Django 5.2.12 on 2026-03-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RbtiSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('axis_type', models.CharField(choices=[('analytic_immersion', 'Analytic / Immersion'), ('critical_empathy', 'Critical / Empathy'), ('practical_expansion', 'Practical / Expansion')], max_length=30)),
                ('order_no', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RbtiSurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytic_score', models.PositiveSmallIntegerField()),
                ('immersion_score', models.PositiveSmallIntegerField()),
                ('critical_score', models.PositiveSmallIntegerField()),
                ('empathy_score', models.PositiveSmallIntegerField()),
                ('practical_score', models.PositiveSmallIntegerField()),
                ('expansion_score', models.PositiveSmallIntegerField()),
                ('is_retest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RbtiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('axis_1', models.CharField(max_length=30)),
                ('axis_2', models.CharField(max_length=30)),
                ('axis_3', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRbtiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytic_score', models.PositiveSmallIntegerField()),
                ('immersion_score', models.PositiveSmallIntegerField()),
                ('critical_score', models.PositiveSmallIntegerField()),
                ('empathy_score', models.PositiveSmallIntegerField()),
                ('practical_score', models.PositiveSmallIntegerField()),
                ('expansion_score', models.PositiveSmallIntegerField()),
                ('source_type', models.CharField(choices=[('survey', 'Survey'), ('ai_review', 'AI Review'), ('manual_reset', 'Manual Reset')], max_length=20)),
                ('source_ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RbtiSurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rbti.rbtisurveyquestion')),
            ],
        ),
    ]
