# Generated by Django 5.2.12 on 2026-03-27 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rbtisurveysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbti_survey_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rbtisurveyanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rbti.rbtisurveysession'),
        ),
        migrations.AddField(
            model_name='rbtisurveysession',
            name='rbti_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_sessions', to='rbti.rbtitype'),
        ),
        migrations.AddField(
            model_name='userrbtisnapshot',
            name='rbti_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_snapshots', to='rbti.rbtitype'),
        ),
        migrations.AddField(
            model_name='userrbtisnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbti_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rbtisurveyanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_answer_per_question_in_session'),
        ),
    ]
