# Generated by Django 5.2.12 on 2026-05-02 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbti', '0003_update_survey_axis_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='RbtiSurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('choice_text', models.TextField()),
                ('score_value', models.IntegerField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='rbti.rbtisurveyquestion')),
            ],
            options={
                'ordering': ['question__order_no', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='rbtisurveyanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='rbti.rbtisurveychoice'),
        ),
        migrations.AddConstraint(
            model_name='rbtisurveychoice',
            constraint=models.UniqueConstraint(fields=('question', 'label'), name='unique_choice_label_per_question'),
        ),
    ]
