# Generated by Django 5.2.12 on 2026-05-02 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbti', '0004_rbtisurveychoice_rbtisurveyanswer_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbtisurveyanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='rbti.rbtisurveychoice'),
        ),
    ]
